### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by AlexanderYW** [devongovett/font-manager#13]
Am i missing some dependencies or?
I am getting this error 

```
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Electron\font-manager-knockout\node_modules\font-manager\build\Release\fontmanager.node
```

[http://i66.tinypic.com/209t0lg.png](http://i66.tinypic.com/209t0lg.png)

Thanks!

**Comment by devongovett** [comment]
Hmm, not sure. What Windows version are you on?

**Comment by AlexanderYW** [comment]
I'm on Windows 10 pro 64bit

**Comment by rBurgett** [comment]
@AlexanderYW : What are you using for the compiling? Are you using `node-gyp`? If so, are you adding the [headers](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-node-gyp-way)?

**Comment by AlexanderYW** [comment]
I dont think i am, will you provide a small guide with the details on the project

Sorry for the trouble im new at this!

**Comment by rBurgett** [comment]
I've never used Electron before, but I use NW (formerly Node Webkit). Because it is not regular Node, I needed to use `nw-gyp` rather than `node-gyp` which is what most people using Node would use. I was reading about [using native Node modules](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-node-gyp-way) in Electron and I see you have a few options for building native modules. I would suggest you try those three methods and see if one works.

Like NW, Electron uses its own version of V8, so it's important to build it specifically for that. What I do for the application I am using font-manager in is I build each version (32 & 64 bit for Win, OSX, and Linux) separately, outside of the build process of my application. Then I drop in the built packages and have Node check the OS and select the right package at runtime.

My point is, rather than build the native font-manager module as part of your Electron build, you might want to try building it (or them) outside of Electron (with the proper headers or whatever is required) then put the pre-compiled modules into your application.

**Comment by AlexanderYW** [comment]
Thanks i will look into it, I will get back in a week if it worked!

**Comment by AlexanderYW** [comment]
Hey @rBurgett, Not sure what ended up fixing it.... but i think what you wrote made me find the solution

But what i do know was that my config was wrong... i needed this to get it working

```
set npm_config_disturl=https://atom.io/download/atom-shell
set npm_config_target=0.36.0
set npm_config_arch=x64
set npm_config_runtime=electron
```

But great help thanks!
